### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by vazhnov** [tsowell/12-port-s-video-audio-switch#1]
Hello!

I found link to this project from https://hackaday.com/2021/03/30/custom-built-12-port-a-v-switch-keeps-crt-well-fed/

Could you please add information about license of this repository — is it allowed to copy, change and use the code and board schematic files in any purpose?
It would be great to see any popular open source license.

**Comment by tsowell** [comment]
Hi, yes, sorry I forgot that!  I'm releasing the contents of this repository under an MIT license, and I've added the licensing file: (64fa706a436f14960ff93261482801e07a017a8b).  I'm new to hardware licensing, but from what I understand, that should be sufficient.  Please let me know if I did anything wrong though.  Thanks for your interest!

**Comment by vazhnov** [comment]
@tsowell , Thank you!
